### ISSUE TITLE
Unable to register - Something went wrong

### ISSUE THREAD

**Issue by jayrajmulani** [ekanshsinghal/se-group26-proj1#18]
```
c-cqfibhp-shard-00-00.npdziph.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997),ac-cqfibhp-shard-00-02.npdziph.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997),ac-cqfibhp-shard-00-01.npdziph.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997), Timeout: 30s, Topology Description: <TopologyDescription id: 636c259fac2830bc8d7645b3, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-cqfibhp-shard-00-00.npdziph.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-cqfibhp-shard-00-00.npdziph.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')>, <ServerDescription ('ac-cqfibhp-shard-00-01.npdziph.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-cqfibhp-shard-00-01.npdziph.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')>, <ServerDescription ('ac-cqfibhp-shard-00-02.npdziph.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-cqfibhp-shard-00-02.npdziph.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')>]>
127.0.0.1 - - [09/Nov/2022 17:17:23] "POST /register HTTP/1.1" 400 -
```

Hey guys, I was just trying to setup the project on my local machine, I couldn't register a new user. The backend and frontend apps start by following the instructions, I think there is an issue with the MongoDB configuration. I couldnt see any steps on the repo to setup the MongoDB. Do i need to do any additional setup for Mongo? Can you please help?

Here is the screenshot: 

![JobTrakr Error](https://user-images.githubusercontent.com/39649967/200954756-1e285c4e-f987-4dd5-adfd-aea061984d40.png)

**Comment by ekanshsinghal** [comment]
@gowtham-sathyan Can you please look into it.
@jayrajmulani i think Gowtham might need email id's of everyone in your group.

**Comment by jayrajmulani** [comment]
Sure, here is a list of consolidated emails:

jayrajm.mulani@gmail.com, jmulani2@ncsu.edu
yashasya.shah@gmail.com, yshah3@ncsu.edu
anishasc99@gmail.com, aschazho@ncsu.edu
harshilsan7@gmail.com, hsangha@ncsu.edu
dhrumilshah0310@gmail.com, dshah6@ncsu.edu

**Comment by gowtham-sathyan** [comment]
I wasn't sure which email IDs might already be registered on Mongo, so to keep it simple, I added all the ncsu email IDs as project owners. Every ncsu email ID in the given list should have received an invite. I think you guys can change any access if required. Let me know if anything didn't work.

**Comment by jayrajmulani** [comment]
Hi @gowtham-sathyan. Thank you for adding us to the MongoDb account. I am able to access the mongo portal. 
Can you give me a summary of what needs to be done after going to the mongo portal to resolve the above certificate error.. Should I create new creds and update the code?

**Comment by jayrajmulani** [comment]
Also, if we can connect your discord channel / slack channel, it will be really easy to communicate. Can you please share the link here? I couldn't spot it on the repo in the first glance. The QR code on the posters seems to be invalid.

**Comment by gowtham-sathyan** [comment]
Hi @jayrajmulani, this is an issue we haven't encountered before. I had configured the project to allow any IP Address to access the clusters and the email IDs were only for you guys to be able to view on the MongoDB website. The error is probably not due to any permission issue, but if you have tried other solutions and if they haven't worked, let me know. Meanwhile, check this link: https://www.mongodb.com/community/forums/t/mongonetworkerror-unable-to-get-local-issuer-certificate/3518/5
There seem to be many available discussions regarding this issue. Some have even provided solutions to the same. Please try them out and let me know if none of them work. In the worst case, you can start a new project in your MongoDB login and import all the collections we had created (I think there's an option to download and import). This will ensure that you have your own system set up on MongoDB and probably shouldn't have any more issues. 

This is our discord link: https://discord.gg/BY5VwwYr

Feel free to reach out if you have any doubts.

**Comment by jayrajmulani** [comment]
Hi @gowtham-sathyan. I tried to follow the discussions to disable the TLS verification, but its still not working. Do you have any script that I can use to create the initial schema. I have created a new Mongo project. 

<img width="1502" alt="Screenshot 2022-11-24 at 16 13 05" src="https://user-images.githubusercontent.com/39649967/203863887-d39db40a-3b16-4418-bac2-e8c93a84d9a9.png">

Also, the discord invite seems to be invalid. Can you please recheck?

**Comment by gowtham-sathyan** [comment]
Hi @jayrajmulani. I have checked with my teammates and there hasn't been any script used to create the schema. I think it was manually created. Since it is NoSQL, you just have to create the collections. You don't have to specify the schema as you can input any data you want in any format. You can just create the collections (name it like in ours) and connect the website to your new URL. You wouldn't have to create anything else manually.

Also, sorry about the discord url. It was the one given to me and I forwarded it here which might have expired. Please try this url: https://discord.gg/xm4naDjA

Let me know if anything doesn't work or if you have any doubts.

Apart from this, my teammate has a doubt regarding your project. I believe your EduSetu backend is hosted on Oracle (Correct me if I'm wrong), how do we dockerize it and put it in, say, AWS?

**Comment by jayrajmulani** [comment]
Hey @gowtham-sathyan. I figured out a workaround. It should be good enough for now..  I added this flag in the mongo client. tlsAllowInvalidCertificates=True
